/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Test: typeof import('./../components/Test.vue')['default']
    VPFeature: typeof import('./../components/VPFeature.vue')['default']
    VPImage: typeof import('./../components/VPImage.vue')['default']
    VPLink: typeof import('./../components/VPLink.vue')['default']
  }
}
